# when only true,ignore permission control
devMode: true
spring:
  http:
    encodeing:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
server:
  port: 8190

redis:
  hosts:
  password: 123456
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  maxWaitMillis: 1
  testOnBorrow: false
  connectionTimeout: 5000
  soTimeout: 5000
  maxAttempts: 5
  database: 0